name = "feedback-handler"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "RATINGS_KV"
id = "PLACEHOLDER_KV_DEV_ID"

[env.production]
name = "feedback-handler-prod"

[[env.production.kv_namespaces]]
binding = "RATINGS_KV"
id = "PLACEHOLDER_KV_PROD_ID"